# This script is used for debugging the module when using the
# [PowerShell Tools for VisualStudio 2022](https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsVS2022)
Import-Module $PSScriptRoot\RepoBuild.psd1 -Force -Verbose

# Get and show the Functions to export to allow easy updates of the PSD file
# this eliminates most of the error prone tedious nature of manual updates.
RepoBuild\Get-FunctionsToExport

# Test a few variants of versions
$verInfo = Get-ParsedBuildVersionXML -Path (Join-Path $PSScriptRoot '..' '..' 'BuildVersion.xml')
$verInfo['CiBuildIndex'] = ConvertTo-BuildIndex $env:BuildTime
$verInfo['CiBuildName'] = $buildInfo['CiBuildName']

# force env overloads of variables, normally generated by tasks
# but the tasks cannot be used in this build as it is building the tasks
$csemVer = [CSemVer]::New($verInfo)
